---
- name: download and checksum node_exporter binary
  tags:
    - node_exporter
  get_url:
    url: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_tgz }}"
    checksum: "sha256:{{ node_exporter_sha256 }}"

- name: unpack node_exporter tarball
  tags:
    - node_exporter
  unarchive:
    src: "{{ node_exporter_tgz }}"
    dest: "/tmp/"
    copy: false

- name: create node_exporter user
  tags:
    - node_exporter
  user:
    name: node_exporter
    shell: "/bin/false"
    comment: "node_exporter service user"

- name: check if node_exporter service exists
  tags:
    - node_exporter
  stat:
    path: "/etc/systemd/system/node_exporter.service"
  register: checked

- name: stop node_exporter service if it exists
  tags:
    - node_exporter
  when: checked.stat.exists
  service:
    name: node_exporter
    state: stopped

- name: copy node_exporter binary to /usr/local/bin
  tags:
    - node_exporter
  command: "cp /tmp/{{ node_exporter_dir }}/node_exporter /usr/local/bin/"

- name: set permissions on node_exporter binary
  tags:
    - node_exporter
  file:
    path: "/usr/local/bin/node_exporter"
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: create node_exporter systemd unit
  tags:
    - node_exporter
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"

- name: reload systemd configurations
  tags:
    - node_exporter
  command: "systemctl daemon-reload"

- name: create node_exporter textfile collector directory
  tags:
    - node_exporter
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: download smartmon.sh textfile collector script
  tags:
    - node_exporter
  get_url:
    url: "https://raw.githubusercontent.com/prometheus-community/node-exporter-textfile-collector-scripts/master/smartmon.sh"
    dest: "{{ node_exporter_textfile_dir }}/smartmon.sh"
    mode: 0744

- name: enable smartmon.sh cronjob
  tags:
    - node_exporter
  cron:
    name: smartmon.sh
    minute: "*"
    user: root
    job: "{{ node_exporter_textfile_dir }}/smartmon.sh > {{ node_exporter_textfile_dir }}/smartmon.prom"

- name: start node_exporter service
  tags:
    - node_exporter
  service:
    name: node_exporter
    state: started
    enabled: true

- name: remove temporary node_exporter files
  tags:
    - node_exporter
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/{{ node_exporter_dir }}"
    - "{{ node_exporter_tgz }}"
