---
- name: download and checksum hdhomerun_exporter binary
  tags:
    - hdhomerun_exporter
  get_url:
    url: "{{ hdhomerun_exporter_url }}"
    dest: "/tmp/hdhomerun_exporter"
    checksum: "sha256:{{ hdhomerun_exporter_sha256 }}"

- name: create hdhomerun_exporter user
  tags:
    - hdhomerun_exporter
  user:
    name: hdhomerun_exporter
    shell: "/bin/false"
    comment: "hdhomerun_exporter service user"

- name: check if hdhomerun_exporter service exists
  tags:
    - hdhomerun_exporter
  stat:
    path: "/etc/systemd/system/hdhomerun_exporter.service"
  register: checked

- name: stop hdhomerun_exporter service if it exists
  tags:
    - hdhomerun_exporter
  when: checked.stat.exists
  service:
    name: hdhomerun_exporter
    state: stopped

- name: copy hdhomerun_exporter binary to {{ host_bin_path }}
  tags:
    - hdhomerun_exporter
  command: "cp /tmp/hdhomerun_exporter {{ host_bin_path }}/"

- name: set permissions on hdhomerun_exporter binary
  tags:
    - hdhomerun_exporter
  file:
    path: "{{ host_bin_path }}/hdhomerun_exporter"
    owner: hdhomerun_exporter
    group: hdhomerun_exporter
    mode: 0755

- name: create hdhomerun_exporter systemd unit
  tags:
    - hdhomerun_exporter
  template:
    src: hdhomerun_exporter.service.j2
    dest: "/etc/systemd/system/hdhomerun_exporter.service"

- name: reload systemd configurations
  tags:
    - hdhomerun_exporter
  command: "systemctl daemon-reload"

- name: start hdhomerun_exporter service
  tags:
    - hdhomerun_exporter
  service:
    name: hdhomerun_exporter
    state: started
    enabled: true

- name: remove temporary files
  tags:
    - hdhomerun_exporter
  file:
    path: "/tmp/hdhomerun_exporter"
    state: absent
