---
- name: check if mdlayher.com service exists
  tags:
    - mdlayhercom
  stat:
    path: "/lib/systemd/system/mdlayher.com.service"
  register: checked

- name: stop mdlayher.com service if it exists
  tags:
    - mdlayhercom
  when: checked.stat.exists
  service:
    name: mdlayher.com
    state: stopped

- name: download and checksum mdlayher.com binary
  tags:
    - mdlayhercom
  get_url:
    url: "{{ mdlayhercom_url }}"
    dest: "/usr/local/bin/mdlayher.com"
    checksum: "sha256:{{ mdlayhercom_sha256 }}"

- name: create mdlayhercom user
  tags:
    - mdlayhercom
  user:
    name: mdlayhercom
    shell: "/bin/false"
    comment: "mdlayhercom service user"

- name: grant capabilities to mdlayher.com binary
  tags:
    - mdlayhercom
  capabilities:
    path: "/usr/local/bin/mdlayher.com"
    capability: "cap_net_bind_service+ep"
    state: present

- name: set permissions on mdlayher.com binary
  tags:
    - mdlayhercom
  file:
    path: "/usr/local/bin/mdlayher.com"
    owner: mdlayhercom
    group: mdlayhercom
    mode: 0755

- name: create mdlayher.com systemd unit
  tags:
    - mdlayhercom
  template:
    src: mdlayher.com.service.j2
    dest: "/lib/systemd/system/mdlayher.com.service"

- name: reload systemd configurations
  tags:
    - mdlayhercom
  command: "systemctl daemon-reload"

- name: start mdlayher.com service
  tags:
    - mdlayhercom
  service:
    name: mdlayher.com
    state: started
    enabled: yes