---
- name: update package lists
  tags:
    - base
  apt:
    update_cache: yes

- name: install common packages
  tags:
    - base
  apt: pkg={{ item }} state=installed
  with_items:
   - byobu
   - git
   - htop
   - jq
   - tmux
   - tree
   - linux-generic-hwe-16.04
   - lm-sensors
   - zfsutils-linux
   - hddtemp

- name: upgrade all packages
  tags:
    - base
  apt:
    upgrade: dist
